### ISSUE TITLE
Carga de clase de Java 26/04

### ISSUE THREAD

**Issue by MartinT2222** [CodeSystem2022/TercerSemestreMateCoders#6]

**Comment by federicopfund** [comment]
@SabrinaJudith 
@federicopfund 

Hola comunidad: Subimos [avances](https://github.com/CodeSystem2022/TercerSemestreMateCoders/tree/fede/PROGRAMACION/Leccion03), específicamente los ejercicios de la lección 3. la lección 3 es un package y las correspondientes carpetas internas son subpackages.
